services:
  db:
    container_name: postgres_dev
    ports:
      - "5432:5432"
    volumes:
      # - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - devnet

  adminer:
    image: adminer
    container_name: adminer_dev
    restart: always
    ports:
      - "8081:8080"
    networks:
      - devnet

networks:
  devnet:
    name: appnet